 SELECT * FROM book_store.books;
 
1. How many total customers are in the database?
2. List the top 5 customers who spent the most.
3. What is the average order amount?
4. How many orders were placed in 2024?
5. Which customer placed the most number of orders?
6. Find the total revenue generated by the bookstore.
7. List all customers who have never placed an order.
8. Get the number of orders placed by each customer.
9. Show all customer names and their emails.
10. Find the total number of orders placed.
11. Show order IDs and their order dates.
12. List names of customers who placed an order in 2025.
13. How many customers have the same name?
14. Find all orders with amount greater than ₹1000.
15. Show the 10 most recent orders.

